linters:
  LineLength:
      max: 200

  ClassesBeforeIds:
    enabled: false

  ImplicitDiv:
    enabled: false

  UnnecessaryStringOutput:
    enabled: false

  RuboCop:
    ignored_cops:
      - Style/StringLiterals
      - Style/SpaceInsideHashLiteralBraces

