AllCops:
  RunRailsCops: true
  Exclude:
    - '**/metadata.rb'
    - '**/*.gemspec'
    - '**/version.rb'

Style/ClassAndModuleChildren:
  Enabled: false
Style/CollectionMethods:
  Enabled: false
Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 160
Metrics/MethodLength:
  Max: 25
