---
exclude:
  - 'coverage/**'
  - 'stepdown/**'
  - 'tmp/**'
  - 'vendor/assets/stylesheets/**'

linters:
  Comment:
    enabled: false
  SelectorFormat:
    enabled: false
  ColorVariable:
    enabled: false
